### ISSUE TITLE
s* instead of s# with PyArg_ParseTupleAndKeywords

### ISSUE THREAD

**Issue by frensjan** [python-lz4/python-lz4#16]
In python-lz4 ```s#``` is used in e.g. the ```lz4.decompress``` method. I've got ```bytearray``` objects I'm decompression and I currently have to create an immutable ```bytes``` object out of them for compatibility with lz4. While I understand that lz4 will threat the bytes to be decompressed as immutable, accepting only immutable ```bytes``` objects forces a memory copy when the data is in a ```bytearray```. Any posibility ```s#``` could be changed to ```s*```?

**Comment by jonathanunderwood** [comment]
Hm. Good suggestion. I'll look at this after I cut the 0.9 release (next weekend). I need to give some thoughts as to the side effects of that change.

**Comment by jonathanunderwood** [comment]
So, this is a bit tricky, since s* is supported only by Python3. Actually, I guess this issue only arises with Python 3 anyway, right? So, an option would be to conditionalize the argument parsing statement depending on Py2 vs Py3. Am I missing anything? Do you have a better idea for making this change supporting both Python 2 and Python 3 ?

**Comment by frensjan** [comment]
The lib I'm developing is py3 indeed. I'm not sure what the best way forward on this while staying compatible with both python 2 as 3.

In https://docs.python.org/2/c-api/arg.html I do read about '''s*''' in py2, but with different documentation.

> the caller is responsible for calling PyBuffer_Release

is especially problematic I guess.

I you'd want to discern between py2 and 3 in how to deal with this, you could even consider '''y*''' as it doesn't accept a Unicode string (which is desirable I presume).

**Comment by jonathanunderwood** [comment]
Looking more into it, I am not sure there's actually a way to pass either a bytes or bytearray object into the same parameter in an extension module. As far as I can, in Python 3 see s* still expects a bytes object, and you have to explicitly use something like Y for bytearray. Unless I've misunderstood the docs completely.

I'll continue to play, but right now, I think the only option would be have separate functions to use with bytearray types.

**Comment by jonathanunderwood** [comment]
Note to self: the right approach here would be to accept a python object in the args (O type), and then use introspection to get the size and buffer whether it's a bytes or bytesarray type.

https://docs.python.org/3/c-api/bytes.html
https://docs.python.org/3/c-api/bytearray.html

**Comment by jonathanunderwood** [comment]
The `py3_byte_array` branch now accepts a bytearray object being passed to compress and decompress.

I am now wondering what these functions should return. Up to know they've returns a bytes/str object. Perhaps they should return a bytearray object in Python 3? Or, perhaps they should return a bytes object if passed a bytes object for source, and return a bytearray object if source is a bytearray. Thoughts welcome!

**Comment by jonathanunderwood** [comment]
I have decided, on Python 3, to always return a bytearray object.

**Comment by jonathanunderwood** [comment]
Fixed in 0.9.2.

**Comment by jd** [comment]
You should have probably released a major version bump as this broke the API compatibility. :(

**Comment by jonathanunderwood** [comment]
Well, in all the tests I ran, it didn't seem to break compatibility. Can you provide a breaking test case that I could add to the test suite?

**Comment by jd** [comment]
It's pretty simple: it breaks compatibility because some projects such as https://github.com/sileht/pycradox requires `bytes` as input and check the type (`isinstance`). I'm not saying it's a good practice on their side and I've opened a bug at https://github.com/sileht/pycradox/issues/1 but that'd still broke Gnocchi http://gnocchi.xyz/ :)

**Comment by pitrou** [comment]
I'm sorry to chime in a bit late, but I think the solution here is a bit confused. The right way to solve this issue would really have been to use the `s*` specifier, so that many input types are accepted automatically (such memoryviews, bytearrays but also Numpy arrays).

Also, having to call PyBuffer_Release() at the end is a feature: it ensures that the input doesn't get mutated while you are acting on it (think what happens if one threads starts to lz4-compress a bytearray and the other thread reallocates the bytearray when shrinking it).

**Comment by pitrou** [comment]
Or, as @frensjan mentioned, use `y*` on py3 and `s*` on py2 (which both fill in a `Py_buffer`, so there's little duplication required).

**Comment by pitrou** [comment]
Also, I don't think returning a bytearray, while not detrimental, does not make particular sense. bytearrays are useful if you want to mutate the data; otherwise there's not much use to them. Also, some APIs only accept bytes objects (such as lz4 did :-)), so it's generally better to return bytes objects.

**Comment by pitrou** [comment]
Ok, I see that you already backed out on the decision to return a bytearray :-)
