### ISSUE TITLE
Reflect frame.decompress() return change in doc

### ISSUE THREAD

**Issue by decibelcooper** [python-lz4/python-lz4#60]
Hi @jonathanunderwood et al, thanks for the new release and the great work.  With the new release I find that frame.decompress() now returns a tuple, with the byte string and an integer, but the [documentation](http://python-lz4.readthedocs.io/en/latest/lz4.frame.html#lz4.frame.decompress) doesn't seem to reflect the change.

**Comment by jonathanunderwood** [comment]
Oh dear, that one slipped through. Thanks for the report. The integer
returned is the number of bytes read from the input data. I'll update the
docs for the next release.

Thanks for the report, it's always really helpful to get any reports on doc
errors.

**Comment by decibelcooper** [comment]
Thanks, happy to help!

**Comment by excentro123** [comment]
Hello. Is where any way to make lz4 return str, as it did before 0.12?
Thanks

**Comment by jonathanunderwood** [comment]
> Is where any way to make lz4 return str, as it did before 0.12?

Not at present. I have to admit, I went back and forwards on this a bit. Let me explain the rationale.

Consider the use case where the user calls `lz4.frame.decompress(data)` where `data` contains a frame (or part of a frame) of compressed data, ending with the end of frame marker. After the end of frame, `data` could contain more data. That could either be another LZ4 frame, or just other useful data for the application. When `lz4.frame.decompress(data)` returns, it will only have consumed data up until the end of the frame, and the user will be interested to know where to begin reading the extra data from. The returned number of bytes (`bytes_read`) facilitates the user doing something like `extra_data=data[bytes_read:]`. Without returning the `bytes_read`, the user wouldn't readily know where the frame had ended. I have had reports in the past of people wanting to use `lz4.frame.decompress` with data like this (indeed the origins of this functionality come from a pull request).

Ok, so that's the use case, and I implemented the simplest thing possible, requiring the least memory consumption (an alternative would have been to return a new string with the unused data). However, I am not married to this, necessarily.

A different solution would be to have a boolean option for `lz4.frame.decompress`, say `return_bytes_read`, which defaults to `False`: 
* If `return_bytes_read` is `False` then `lz4.frame.decompress` returns only the uncompressed data.
* If `return_bytes_read` is `True` then `lz4.frame.decompress` returns the uncompressed data and `bytes_read` as a tuple.

Would welcome your thoughts on that, and alternative suggestions.

**Comment by excentro123** [comment]
I think boolean option is a good idea. Thanks.

**Comment by jonathanunderwood** [comment]
@decibelcooper any thoughts/opinions?

**Comment by jonathanunderwood** [comment]
The boolean is now implemented and documented on the `return_bytes_read` branch. Testing appreciated.

**Comment by jonathanunderwood** [comment]
I have now cut a new release (0.13.0) with this change. I'll close this issue, but please open a new issue if you find a problem!

**Comment by decibelcooper** [comment]
I think the bool option that defaults to old return behavior is a good idea.  Thanks!
