### ISSUE TITLE
Can't install from pip to a fresh virtualenv: No module named 'pkgconfig'

### ISSUE THREAD

**Issue by jdufresne** [python-lz4/python-lz4#75]
The lz4 package fails to install to a fresh virtualenv with the error. Here is a simple runnable script that demonstrates:

```bash
#!/bin/bash

rm -rf venv
python3 -m venv venv
. venv/bin/activate
pip install lz4
```

Actual result:

```
$ ./runtest.sh 
Collecting lz4
  Using cached lz4-0.14.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-vbudxya6/lz4/setup.py", line 7, in <module>
        import pkgconfig
    ModuleNotFoundError: No module named 'pkgconfig'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-vbudxya6/lz4/
```

Expected result:

Should install.

**Comment by jonathanunderwood** [comment]
Yes, the pkgconfig package needs to be present in the virtualenv ahead of trying to install lz4, as the lz4 `setup.py` script needs it. Running a `pip install pkgconfig` ahead of `pip install lz4` will fix it. Unfortunately, since it's a requirement of the `setup.py` script, there's no easy way to have pkgconfig automatically install as far as I can see.
