### ISSUE TITLE
Cannot seem to read from node-lz4

### ISSUE THREAD

**Issue by gappleto97** [python-lz4/python-lz4#8]
Your library produces this when compressing 'a':

`b'\x01\x00\x00\x00\x10a'`

[node-lz4](https://github.com/pierrec/node-lz4) produces this when compressing 'a':

`b'\x04"M\x18dp\xb9\x02\x00\x00\x00\x10a\x00\x00\x00\x00Vt\rU'`

Neither library can decode the other's output. Is there any chance you could try to make these libraries compatible, since both are supposed to use the same compression?

See: https://github.com/pierrec/node-lz4/issues/48

**Comment by jonathanunderwood** [comment]
This is using the block format, presumably? Interoperability with the block
format is tricky, since how the header (eg. how to include the size) etc is
left up to the implementation. Hence incompatibilities occur.

The frame format solves this in an interoperable way. I've implemented
support for that in master, but haven't pushed a release with that yet.

I could maybe add a compatibility wrapper for nodes implementation. What
are the details of that?

**Comment by gappleto97** [comment]
@pierrec said that the incompatibility arises because you're using the block format, where the stream format is the normally supported one.

They also implemented the block format, but the way they did it is fairly inconvenient to use, and given the choice, I think I'd rather have access to their stream API.

**Comment by jonathanunderwood** [comment]
Right now, I am focused on getting a release finished with block and frame
supported. once that's done, I'll look at streams.

Note that the stream format has the same problem as blocks in terms of
interoperability.

Frames guarantee interoperability and should, according to the lz4 author,
be the generally preferred api.

**Comment by jonathanunderwood** [comment]
Closing this, as it's really not in scope at this time. I'd welcome  a PR implementing stream support, but I am not working on it until frame support is finished.
